import type {
  MedicalReport,
  Meeting,
  MeetingActionItem,
  Patient,
  PatientAuditLog,
  PatientCase,
  Rank,
  Specialization,
  StaffAbsence,
  StaffEvaluation,
  StaffProfile,
  StaffReward,
  StaffStrikepointEntry,
} from "@/types/domain";

export const mockRanks: Rank[] = [
  { id: "rank-1", code: "stagiair", name: "Stagiair", weight: 10, baseSalary: 1500 },
  { id: "rank-2", code: "ambulancier", name: "Ambulancier", weight: 20, baseSalary: 3200 },
  { id: "rank-3", code: "senior", name: "Senior EMS", weight: 30, baseSalary: 3800 },
  { id: "rank-4", code: "leiding", name: "Leiding", weight: 40, baseSalary: 5000 },
];

export const mockSpecializations: Specialization[] = [
  { id: "spec-1", code: "spoed", name: "Spoedzorg", salaryBonus: 250 },
  { id: "spec-2", code: "intake", name: "Intake", salaryBonus: 150 },
  { id: "spec-3", code: "opleiding", name: "Opleiding", salaryBonus: 400 },
  { id: "spec-4", code: "trauma", name: "Trauma team", salaryBonus: 350 },
];

export const mockStaffProfiles: StaffProfile[] = [
  {
    id: "demo-user",
    email: "demo@ems.local",
    fullName: "Demo EMS gebruiker",
    citizenId: "EMS-001",
    callSign: "EMS-001",
    rankId: "rank-4",
    rankName: "Leiding",
    active: true,
    statusOverride: "actief",
    specializationIds: ["spec-3"],
    specializationNames: ["Opleiding"],
    toolPassword: "demodemo",
    phone: "0470 00 00 01",
    joinedAt: "2024-03-01",
    lastModifiedAt: "2026-05-15T18:00:00Z",
    salaryMonthly: null,
    strikePoints: 0,
  },
  {
    id: "sp-001",
    email: "l.verhaegen@ems.local",
    fullName: "Lotte Verhaegen",
    citizenId: "EMS-14210",
    callSign: "EMS-14210",
    rankId: "rank-3",
    rankName: "Senior EMS",
    active: true,
    statusOverride: "afwezig",
    specializationIds: ["spec-1", "spec-4"],
    specializationNames: ["Spoedzorg", "Trauma team"],
    toolPassword: "demodemo",
    phone: "0471 42 10 55",
    joinedAt: "2024-09-18",
    lastModifiedAt: "2026-05-14T20:10:00Z",
    salaryMonthly: null,
    strikePoints: 1,
  },
  {
    id: "sp-002",
    email: "m.desmet@ems.local",
    fullName: "Milan De Smet",
    citizenId: "EMS-13887",
    callSign: "EMS-13887",
    rankId: "rank-2",
    rankName: "Ambulancier",
    active: true,
    statusOverride: "afwezig",
    specializationIds: ["spec-1"],
    specializationNames: ["Spoedzorg"],
    toolPassword: "demodemo",
    phone: "0472 38 87 10",
    joinedAt: "2025-02-11",
    lastModifiedAt: "2026-05-15T19:24:43Z",
    salaryMonthly: null,
    strikePoints: 2,
  },
  {
    id: "sp-003",
    email: "a.idrissi@ems.local",
    fullName: "Amina Idrissi",
    citizenId: "EMS-14762",
    callSign: "EMS-14762",
    rankId: "rank-2",
    rankName: "Ambulancier",
    active: false,
    statusOverride: "non-actief",
    specializationIds: ["spec-2"],
    specializationNames: ["Intake"],
    toolPassword: "demodemo",
    phone: "0473 47 62 20",
    joinedAt: "2025-05-08",
    lastModifiedAt: "2026-05-11T08:10:00Z",
    salaryMonthly: null,
    strikePoints: 0,
  },
  {
    id: "sp-004",
    email: "n.peeters@ems.local",
    fullName: "Noah Peeters",
    citizenId: "EMS-15018",
    callSign: "EMS-15018",
    rankId: "rank-1",
    rankName: "Stagiair",
    active: true,
    statusOverride: "actief",
    specializationIds: ["spec-3"],
    specializationNames: ["Opleiding"],
    toolPassword: "demodemo",
    phone: "0474 50 18 66",
    joinedAt: "2026-04-07",
    lastModifiedAt: "2026-05-14T14:10:00Z",
    salaryMonthly: null,
    strikePoints: 0,
  },
];

export const mockStaffEvaluations: StaffEvaluation[] = [
  {
    id: "eval-001",
    employeeProfileId: "sp-002",
    evaluatorProfileId: "demo-user",
    title: "Evaluatie Q2 interventie-kwaliteit",
    summary: "Sterke communicatie op scene, aandacht nodig voor overdrachtsnotities.",
    content: {
      evaluationPeriod: "April 2026",
      strengths: "Rustig onder druk, duidelijke taakverdeling, goede patiëntbenadering.",
      attentionPoints: "Meer detail in overdrachtsnotities en dossierafwerking.",
      developmentPlan: "Twee shiften meelopen met opleidingsteam en checklist gebruiken.",
      outcome: "Positief met opvolging.",
    },
    createdAt: "2026-05-10T15:00:00Z",
    updatedAt: "2026-05-10T15:00:00Z",
  },
  {
    id: "eval-002",
    employeeProfileId: "sp-004",
    evaluatorProfileId: "sp-001",
    title: "Startbeoordeling stageblok",
    summary: "Goede werkhouding en leercurve, nog coaching nodig bij trauma-opstart.",
    content: {
      evaluationPeriod: "Mei 2026",
      strengths: "Punctueel, leergierig, correcte basiszorg.",
      attentionPoints: "Meer zekerheid nodig in triage en materiaalvoorbereiding.",
      developmentPlan: "Wekelijkse feedbackmomenten met mentor en extra scenario-oefening.",
      outcome: "Voortzetten stageblok.",
    },
    createdAt: "2026-05-14T10:30:00Z",
    updatedAt: "2026-05-14T10:30:00Z",
  },
];

export const mockStaffAbsences: StaffAbsence[] = [
  {
    id: "abs-001",
    profileId: "sp-003",
    absenceType: "Ziekte",
    startDate: "2026-05-12",
    endDate: "2026-05-18",
    reason: "Herstelperiode na medische ingreep.",
    status: "goedgekeurd",
    decidedBy: "demo-user",
    createdAt: "2026-05-11T08:10:00Z",
  },
  {
    id: "abs-002",
    profileId: "sp-001",
    absenceType: "Opleiding extern",
    startDate: "2026-05-21",
    endDate: "2026-05-22",
    reason: "Bijscholing advanced trauma care.",
    status: "aangevraagd",
    decidedBy: null,
    createdAt: "2026-05-14T18:40:00Z",
  },
];

export const mockStaffRewards: StaffReward[] = [
  {
    id: "reward-001",
    profileId: "sp-001",
    title: "Trauma inzet commendatie",
    description: "Erkenning voor kalme leiding tijdens complexe multi-casualty inzet.",
    amount: 350,
    grantedBy: "demo-user",
    grantedAt: "2026-04-26T19:45:00Z",
  },
  {
    id: "reward-002",
    profileId: "sp-002",
    title: "Kwaliteitsbonus dossierafwerking",
    description: "Bonus na sterke maandscore op interventieverslagen en overdracht.",
    amount: 150,
    grantedBy: "demo-user",
    grantedAt: "2026-05-02T12:00:00Z",
  },
  {
    id: "reward-003",
    profileId: "sp-004",
    title: "Stagebeloning",
    description: "Positieve beoordeling van mentor en snelle progressie in opleidingsblok.",
    amount: 75,
    grantedBy: "sp-001",
    grantedAt: "2026-05-14T14:10:00Z",
  },
];

export const mockStaffStrikepointEntries: StaffStrikepointEntry[] = [
  {
    id: "strike-001",
    profileId: "sp-001",
    delta: 1,
    reason: "Te laat bij shiftbriefing zonder geldige melding.",
    createdBy: "demo-user",
    createdAt: "2026-04-11T06:45:00Z",
    resolvedAt: null,
    resolvedBy: null,
    resolvedReason: null,
  },
  {
    id: "strike-002",
    profileId: "sp-002",
    delta: 1,
    reason: "Onvolledig interventieverslag na nachtshift.",
    createdBy: "demo-user",
    createdAt: "2026-03-23T09:20:00Z",
    resolvedAt: null,
    resolvedBy: null,
    resolvedReason: null,
  },
  {
    id: "strike-003",
    profileId: "sp-002",
    delta: 1,
    reason: "Materiaalcontrole niet correct afgesloten.",
    createdBy: "sp-001",
    createdAt: "2026-04-29T18:10:00Z",
    resolvedAt: null,
    resolvedBy: null,
    resolvedReason: null,
  },
];

export const mockPatients: Patient[] = [
  {
    id: "p-001",
    citizenId: "CIT-22014",
    fullName: "Lena Verhaegen",
    birthDate: "1998-04-12",
    phone: "0499 20 14 01",
    emergencyContactName: "Mauro Verhaegen",
    emergencyContactPhone: "0476 11 24 09",
    bloodType: "A+",
    allergies: ["Penicilline"],
    medications: ["Ibuprofen indien nodig"],
    chronicConditions: ["Astma"],
    medicalWarnings: ["Allergische reactie op penicilline in dossier vermelden"],
    warningBadges: ["ALLERGIE"],
    status: "opgenomen",
    createdBy: "demo-user",
    createdAt: "2026-05-13T19:50:00Z",
    updatedBy: "demo-user",
    updatedAt: "2026-05-13T21:10:00Z",
    notes: "Recente opname na verkeersincident. Allergie voor penicilline.",
  },
  {
    id: "p-002",
    citizenId: "CIT-19103",
    fullName: "Milan De Smet",
    birthDate: "1987-10-03",
    phone: "0488 91 03 44",
    emergencyContactName: "Sarah De Smet",
    emergencyContactPhone: "0492 60 33 18",
    bloodType: "O+",
    allergies: [],
    medications: ["Metformine"],
    chronicConditions: ["Diabetes type 2"],
    medicalWarnings: ["Let op glycemiewaarden bij langere observatie"],
    warningBadges: ["DIABETES"],
    status: "stabiel_ontslagen",
    createdBy: "sp-001",
    createdAt: "2026-05-09T13:10:00Z",
    updatedBy: "demo-user",
    updatedAt: "2026-05-09T16:20:00Z",
    notes: "Herhaald consult voor schouderklachten en stressreacties.",
  },
  {
    id: "p-003",
    citizenId: "CIT-17622",
    fullName: "Amina Idrissi",
    birthDate: "2001-06-22",
    phone: "0477 62 21 88",
    emergencyContactName: "Youssef Idrissi",
    emergencyContactPhone: "0465 74 88 21",
    bloodType: "B-",
    allergies: [],
    medications: [],
    chronicConditions: [],
    medicalWarnings: ["Agressierisico gemeld door dispatch bij eerdere interventie"],
    warningBadges: ["AGRESSIERISICO", "POLITIE BETREKKEN"],
    status: "observatie",
    createdBy: "sp-002",
    createdAt: "2026-05-14T08:00:00Z",
    updatedBy: "sp-002",
    updatedAt: "2026-05-14T10:05:00Z",
    notes: "Observatie na oververmoeidheid, geen actieve medicatie.",
  },
  {
    id: "p-004",
    citizenId: "CIT-25018",
    fullName: "Noah Peeters",
    birthDate: "1995-01-18",
    phone: "0468 50 18 30",
    emergencyContactName: "Elke Peeters",
    emergencyContactPhone: "0478 11 50 18",
    bloodType: "AB+",
    allergies: ["Latex"],
    medications: ["Oxycodon volgens schema"],
    chronicConditions: ["Chronische rugklachten"],
    medicalWarnings: ["Forensische opvolging lopend na val van hoogte"],
    warningBadges: ["ALLERGIE", "FORENSISCH DOSSIER"],
    status: "forensisch_politie",
    createdBy: "demo-user",
    createdAt: "2026-05-15T00:10:00Z",
    updatedBy: "demo-user",
    updatedAt: "2026-05-15T07:30:00Z",
    notes: "Lopend dossier met meerdere trauma-updates.",
  },
];

export const mockCases: PatientCase[] = [
  {
    id: "c-001",
    patientId: "p-001",
    title: "Verkeersongeval A15",
    summary: "Complex dossier met observatie, beeldvorming en opvolging na thoraxtrauma.",
    status: "open",
    openedAt: "2026-05-13T19:40:00Z",
  },
  {
    id: "c-002",
    patientId: "p-002",
    title: "Controle schouder en mobiliteit",
    summary: "Gespecialiseerde opvolging voor mobiliteit en pijnbeheer na eerdere interventie.",
    status: "afgesloten",
    openedAt: "2026-05-09T13:15:00Z",
    closedAt: "2026-05-09T16:20:00Z",
  },
  {
    id: "c-003",
    patientId: "p-003",
    title: "Observatie uitputting",
    summary: "Kortdurende case voor observatie, risico-inschatting en gerichte opvolging.",
    status: "open",
    openedAt: "2026-05-14T08:05:00Z",
  },
  {
    id: "c-004",
    patientId: "p-004",
    title: "Trauma na val van hoogte",
    summary: "Complex trauma met forensische context en multidisciplinaire opvolging.",
    status: "open",
    openedAt: "2026-05-15T00:12:00Z",
  },
];

export const mockReports: MedicalReport[] = [
  {
    id: "r-001",
    patientId: "p-001",
    caseId: "c-001",
    type: "trauma",
    title: "Traumarapport verkeersongeval A15",
    summary: "Patiënt stabiel na initiële triage met thoracale pijn en schaafletsels.",
    content: {
      incidentLocation: "A15, afrit noord",
      mechanism: "Frontale botsing bestuurder",
      triageLevel: "Oranje",
      consciousness: "Alerte patiënt, GCS 15",
      injuriesSummary:
        "Thoracale pijn links, schaafwonden aan onderarm, vermoedelijke kneuzing.",
      vitals: "Pols 98, saturatie 97%, bloeddruk 132/84",
      interventions: "Immobilisatie, pijnscore afgenomen, monitoring tijdens transport.",
      transportDecision: "Transport naar spoed voor observatie en RX.",
      followUp: "Opname ter observatie en herbeoordeling na beeldvorming.",
    },
    authorProfileId: "demo-user",
    createdAt: "2026-05-13T20:05:00Z",
    updatedAt: "2026-05-13T20:05:00Z",
  },
  {
    id: "r-002",
    patientId: "p-001",
    caseId: "c-001",
    type: "opname",
    title: "Opnamerapport observatie thoraxtrauma",
    summary:
      "Patiënt opgenomen ter observatie na verkeersongeval met aanhoudende thoracale pijn.",
    content: {
      admissionReason: "Observatie na thoraxtrauma en pijncontrole",
      referringUnit: "Spoed",
      attendingDoctor: "Dr. A. Mertens",
      supportingStaff: "Verpleegkundige S. Jacobs",
      clinicalStatus: "Hemodynamisch stabiel, klachten bij diepe inspiratie",
      provisionalDiagnosis: "Thoraxcontusie links, oppervlakkige schaafletsels",
      startedCare: "Observatie, pijnregistratie, vitale parameters opvolgen",
      medicationPlan: "Pijnstilling volgens schema, evaluatie om de 4 uur",
      admissionPlan: "Nachtobservatie met herbeoordeling in de ochtend",
      wardNotes: "Mobilisatie op geleide van pijn, saturatie monitoren",
    },
    authorProfileId: "demo-user",
    createdAt: "2026-05-13T21:10:00Z",
    updatedAt: "2026-05-13T21:10:00Z",
  },
];

export const mockPatientAuditLogs: PatientAuditLog[] = [
  {
    id: "pa-001",
    patientId: "p-001",
    action: "patient_created",
    actorProfileId: "demo-user",
    actorName: "Demo EMS gebruiker",
    summary: "Patiëntenfiche aangemaakt na verkeersongeval.",
    createdAt: "2026-05-13T19:50:00Z",
    details: { source: "spoedintake" },
  },
  {
    id: "pa-002",
    patientId: "p-001",
    action: "report_created",
    actorProfileId: "demo-user",
    actorName: "Demo EMS gebruiker",
    summary: "Traumarapport toegevoegd aan dossier.",
    createdAt: "2026-05-13T20:05:00Z",
    details: { reportId: "r-001", reportType: "trauma" },
  },
  {
    id: "pa-003",
    patientId: "p-003",
    action: "case_created",
    actorProfileId: "sp-002",
    actorName: "Milan De Smet",
    summary: "Observatiecase geopend.",
    createdAt: "2026-05-14T08:05:00Z",
    details: { caseId: "c-003" },
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: "mtg-001",
    title: "Shiftplanning weekendploeg",
    purpose: "Beschikbaarheid en bezetting voor het weekend vastleggen.",
    location: "Briefingzaal A",
    requestedDate: "2026-05-22",
    participantProfileIds: ["demo-user", "sp-001", "sp-002"],
    status: "gepland",
    requestedBy: "sp-001",
    decidedBy: "demo-user",
    decisionNote: "Goedgekeurd na controle bezettingsnorm.",
    scheduledStart: "2026-05-22T08:00:00Z",
    scheduledEnd: "2026-05-22T08:45:00Z",
    minutes:
      "Besloten om een extra reserveploeg te voorzien tijdens de piekuren zaterdagavond.",
    followUp: "Planning publiceren in dispatch en opvolgen op vrijdagavond.",
    createdAt: "2026-05-20T12:00:00Z",
    updatedAt: "2026-05-20T15:30:00Z",
  },
  {
    id: "mtg-002",
    title: "Evaluatie trauma-protocol Q2",
    purpose: "Doorlichting van recente trauma-interventies en aanpassingen in workflow.",
    location: "Overleglokaal B",
    requestedDate: "2026-05-24",
    participantProfileIds: ["demo-user", "sp-001", "sp-004"],
    status: "aangevraagd",
    requestedBy: "sp-004",
    decidedBy: null,
    decisionNote: null,
    scheduledStart: null,
    scheduledEnd: null,
    minutes: null,
    followUp: null,
    createdAt: "2026-05-21T07:25:00Z",
    updatedAt: "2026-05-21T07:25:00Z",
  },
];

export const mockMeetingActionItems: MeetingActionItem[] = [
  {
    id: "mai-001",
    meetingId: "mtg-001",
    title: "Reserveploeg zaterdag 18u-23u bevestigen",
    description: "Controle op beschikbaarheid + finale dispatchbevestiging.",
    ownerProfileId: "sp-001",
    dueDate: "2026-05-22",
    status: "in_uitvoering",
    createdBy: "demo-user",
    completedAt: null,
    createdAt: "2026-05-20T15:30:00Z",
    updatedAt: "2026-05-20T16:00:00Z",
  },
  {
    id: "mai-002",
    meetingId: "mtg-001",
    title: "Interne communicatie uitsturen",
    description: "Definitieve planning delen met alle betrokken teams.",
    ownerProfileId: "sp-002",
    dueDate: "2026-05-22",
    status: "open",
    createdBy: "sp-001",
    completedAt: null,
    createdAt: "2026-05-20T15:40:00Z",
    updatedAt: "2026-05-20T15:40:00Z",
  },
];
